<?php

$options_launcher = array (
  'developer' => 'Zhareiv',
  'panel_address' => 'admin-panel',
  'name_script' => 'SharePlus+',
  'script_version' => '1.1.4.1',
  'EdenPHP_name' => 'EdenPHP',
  'EdenPHP_version' => '0.0.0.2',
  'EdenPHP_data_url' => 'https://www.youtube.com/watch?v=S5UEoLeza-o',
  'is_logged_data' => 'ddwPwzODl',
  'lang_admin' => 'english',
  'articles_active' => 'on',
  'comments_active' => 'on',
  'ad_blocker' => 'off',
  'google_analytics' => '',
  'smtp_or_mail' => '',
  'smtp_host' => '',
  'smtp_username' => '',
  'smtp_password' => '',
  'smtp_encryption' => '',
  'smtp_port' => '',
  'crypt_secret_key' => 'zhareiv',
  'crypt_password' => '123456789',
  'ads_one' => '',
  'ads_two' => '',
  'ads_three' => '',
  'add_tag_ad_1' => '',
  'add_tag_ad_2' => '',
  'add_tag_ad_3' => '',
  'add_tag_ad_4' => '',
  'add_tag_ad_5' => '',
  'code' => 'A2',
  'update_youtube_key' => 1569549360,
); 

?>